export const    ADD_INGREDIENT = 'ADD_INGREDIENT', 
                REMOVE_INGREDIENT = 'REMOVE_INGREDIENT',
                SET_INGREDIENTS = 'SET_INGREDIENTS',
                FETCH_ING_FAILED = 'FETCH_ING_FAILED',

                PURCHASE_BURGER_START = 'PURCHASE_BURGER_START',
                PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS',
                PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL'