export const    ADD_INGREDIENT = 'ADD_INGREDIENT', 
                REMOVE_INGREDIENT = 'REMOVE_INGREDIENT',
                SET_INGREDIENTS = 'SET_INGREDIENTS',
                FETCH_ING_FAILED = 'FETCH_ING_FAILED';