export const    INIT_INGREDIENTS = 'INIT_INGREDIENTS',
                ADD_INGREDIENT = 'ADD_INGREDIENT', 
                REMOVE_INGREDIENT = 'REMOVE_INGREDIENT',
                SET_INGREDIENTS = 'SET_INGREDIENTS',
                FETCH_ING_FAILED = 'FETCH_ING_FAILED',

                PURCHASE_BURGER_START = 'PURCHASE_BURGER_START',
                PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS',
                PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL',
                PURCHASE_INIT = 'PURCHASE_INIT',

                FETCH_ORDERS_START = 'FETCH_ORDERS_START',
                FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS',
                FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL',

                AUTH_USER = 'AUTH_USER',
                AUTH_START = 'AUTH_START',
                AUTH_SUCCESS = 'AUTH_SUCCESS',
                AUTH_FAIL = 'AUTH_FAIL',
                AUTH_CHECK_STATE = 'AUTH_CHECK_STATE',
                AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT',
                AUTH_LOGOUT =  'AUTH_LOGOUT',
                AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT',

                SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';